# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
#
# ,--------.      ,--.   ,--. ,--.
# '--.  .--',---.  \  `.'  /,-'  '-.
#    |  |  | .-. :  .'    \ '-.  .-'
#    |  |  \   --. /  .'.  \  |  |
#    `--'   `----''--'   '--' `--'

## Base settings ##
# url:  #the base hostname & protocol for your site e.g. https://www.someone.com
baseurl: /
title: Henry's Blog
description: This is Henry's Blog, a Programmer, a Data Visualiser, a Photographer and an Entrepreneur.

nav_lists:
  - titles:
      en: Résumé
      zh: 简历
      zh-Hans: 简历
    url: /resume.html


## Language & timezone ##
lang: en #the language of your site, eg: en(English), zh(简体中文), zh-Hans(简体中文), zh-Hant(繁體中文)
timezone: Europe/London

## Author & social ##
author:
  name: Henry
  email:  henry@wangqiru.com
  # facebook:  #your Facebook username
  # twitter:  #your Twitter username
  github:  wangqiru
  # googleplus:  #your Google+ username
  # weibo:  #your Weibo username
  # douban:  #your Douban username
  linkedin:  wangqiru

## Comment system (Disqus) ##
disqus:
  # shortname:  #the Disqus shortname for the site

## Google Analytics ##
ga_tracking_id:  UA-77456302-3

## Reading quantity (LeanCloud) ##
leancloud:
  app_id:  QD8MBjeWxoProN3D46TOsBWT-gzGzoHsz
  app_key:  6rYosWYItQajTIaRKGRHDPQv
  app_class:  counter

gitalk:
  clientID: 583d71112097971f54a3
  clientSecret: e288a7631c207c6a83b16c81c0f14658c6304a3c
  repository: wangqiru.github.io
  owner: WangQiru
  admin: WangQiru

  # please refer to https://github.com/gitalk/gitalk for more info.

# mathjax: true

## Paginate ##
paginate: 5
paginate_path: /page:num

## Post excerpts ##
excerpt_separator: <!--more-->
excerpt_type: html # text | html

## Build ##
permalink: date
markdown: kramdown 
github: [metadata]
highlighter: rouge


exclude:
  - Gemfile
  - Gemfile.lock
  - README-*.md
  - README.md
  - jekyll-text-theme.gemspec
  - package-lock.json
  - package.json
  - gulpfile.js
  - npm-debug.log.*
  - /node_modules
  - /vendor
  - _config.dev.yml
  - .travis.yml

## Plugins ##
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jemoji

## Server ##
url: https://www.wangqiru.com
enforce_ssl: www.wangqiru.com

## Development ##
isdebug: false
